source 'http://gems.headshift.local'
source 'http://rubygems.org'
source 'http://gems.github.com'

gem 'rails', '2.3.8'
gem 'headshift-rails'
gem 'yodel_gazetteer', '0.0.11'
gem 'bundler'
gem 'erubis'
gem 'mysql'
